"""
Node: final_decision
Responsibility: Compute overall score, make hiring decision, build final report.
This is the LAST node before END.
Inputs: all scores, all reasoning, all data from previous nodes
Outputs: recommendation, reasoning, pros, cons, risks, confidence, overall_score, final_report
"""
from __future__ import annotations

from typing import Any, Dict

from src.agents.decision_agent import DecisionAgent
from src.graph.state import GraphState


# ── Report badge map ──────────────────────────────────────────────────────────
_DECISION_BADGES: Dict[str, str] = {
    "Strong Hire": "🟢 STRONG HIRE",
    "Hire": "🔵 HIRE",
    "Maybe": "🟡 MAYBE",
    "Reject": "🔴 REJECT",
}


def _build_final_report(state: GraphState, decision: Dict[str, Any]) -> str:
    """
    Build a formatted markdown recruiter report from the full state and decision.

    Args:
        state: The current full GraphState.
        decision: DecisionResult.model_dump() from the decision agent.

    Returns:
        Multi-section markdown string ready for display.
    """
    resume_data = state.get("resume_data", {})
    jd_data = state.get("jd_data", {})
    name = resume_data.get("name", "Candidate") or "Candidate"
    role = jd_data.get("role_title", "Unknown Role") or "Unknown Role"

    score = decision.get("overall_score", 0.0)
    recommendation = decision.get("recommendation", "Maybe")
    badge = _DECISION_BADGES.get(recommendation, f"⚪ {recommendation}")
    confidence_pct = int(decision.get("confidence", 0.0) * 100)

    # Scores
    skill_score = state.get("skill_score", 0.0)
    exp_score = state.get("experience_score", 0.0)
    edu_score = state.get("education_score", 0.0)
    culture_score = state.get("culture_score", 0.0)

    # Skills
    matched = state.get("matched_skills", [])
    missing = state.get("missing_skills", [])
    partial = state.get("partial_skills", [])

    # Culture details
    culture_details = state.get("culture_details", {})

    def skill_list(skills: list[str]) -> str:
        return "`" + "`, `".join(skills) + "`" if skills else "_None_"

    def bullet_list(items: list[str], icon: str = "•") -> str:
        return "\n".join(f"{icon} {item}" for item in items) if items else "_None_"

    # Interview questions
    questions = state.get("interview_questions", [])
    q_md = "\n".join(
        f"{i + 1}. {q}" for i, q in enumerate(questions)
    ) if questions else "_No questions generated._"

    # Culture breakdown table
    culture_rows = ""
    dim_labels = {
        "communication": "💬 Communication",
        "leadership": "👑 Leadership",
        "ownership": "🎯 Ownership",
        "problem_solving": "🧠 Problem Solving",
        "adaptability": "🔄 Adaptability",
    }
    for key, label in dim_labels.items():
        val = culture_details.get(key, 5.0)
        bar = "█" * int(val) + "░" * (10 - int(val))
        culture_rows += f"| {label} | {val:.1f}/10 | `{bar}` |\n"

    report = f"""# 📋 AI Hiring Report

**Candidate:** {name}
**Role Applied For:** {role}

---

## {badge}

### Overall Score: **{score:.1f} / 100**
> Confidence: {confidence_pct}%

---

## 📊 Score Breakdown

| Category | Score | Weight | Weighted |
|---|---|---|---|
| 🛠️ Skill Match | {skill_score:.1f}/100 | 40% | {skill_score * 0.4:.1f} |
| 💼 Experience | {exp_score:.1f}/100 | 30% | {exp_score * 0.3:.1f} |
| 🤝 Culture Fit | {culture_score:.1f}/100 | 20% | {culture_score * 0.2:.1f} |
| 🎓 Education | {edu_score:.1f}/100 | 10% | {edu_score * 0.1:.1f} |
| **Total** | | **100%** | **{score:.1f}** |

---

## ⚡ Skill Analysis

**✅ Matched Skills ({len(matched)}):**
{skill_list(matched)}

**🔶 Partial Matches ({len(partial)}):**
{skill_list(partial)}

**❌ Missing Skills ({len(missing)}):**
{skill_list(missing)}

---

## 🤝 Culture Fit Breakdown

| Dimension | Score | Bar |
|---|---|---|
{culture_rows}
**Notes:** {state.get("culture_reasoning", "_Not available_")}

---

## 💪 Strengths
{bullet_list(decision.get("pros", []), "✅")}

## ⚠️ Concerns
{bullet_list(decision.get("cons", []), "🔸")}

## 🔴 Risks
{bullet_list(decision.get("risks", []), "⚠️")}

---

## 🧠 Hiring Rationale

{decision.get("reasoning", "_Not available_")}

---

## ❓ Recommended Interview Questions

{q_md}

---

*Generated by AI Resume Screening Agent | LangGraph + GPT-4o | Scores are weighted: Skill 40% · Experience 30% · Culture 20% · Education 10%*
""".strip()

    return report


def final_decision_node(state: GraphState) -> Dict[str, Any]:
    """
    LangGraph node — Final Hiring Decision.

    1. Computes the overall weighted score from all component scores.
    2. Calls DecisionAgent for a nuanced recommendation.
    3. Builds the final formatted markdown report.
    """
    agent = DecisionAgent()

    skill_score = state.get("skill_score", 0.0)
    experience_score = state.get("experience_score", 0.0)
    education_score = state.get("education_score", 0.0)
    culture_score = state.get("culture_score", 0.0)

    # Compute weighted score before calling LLM
    overall_score = DecisionAgent.compute_weighted_score(
        skill_score=skill_score,
        experience_score=experience_score,
        education_score=education_score,
        culture_score=culture_score,
    )

    try:
        result = agent.run(
            resume_data=state.get("resume_data", {}),
            jd_data=state.get("jd_data", {}),
            matched_skills=state.get("matched_skills", []),
            missing_skills=state.get("missing_skills", []),
            partial_skills=state.get("partial_skills", []),
            skill_score=skill_score,
            skill_reasoning=state.get("skill_reasoning", ""),
            experience_score=experience_score,
            experience_reasoning=state.get("experience_reasoning", ""),
            education_score=education_score,
            education_reasoning=state.get("education_reasoning", ""),
            culture_score=culture_score,
            culture_reasoning=state.get("culture_reasoning", ""),
            overall_score=overall_score,
        )

        decision_dict = result.model_dump()

        # Build merged state snapshot for report generation
        report_state: GraphState = {**state, "overall_score": result.overall_score}
        final_report = _build_final_report(report_state, decision_dict)

        return {
            "overall_score": result.overall_score,
            "recommendation": result.recommendation,
            "reasoning": result.reasoning,
            "pros": result.pros,
            "cons": result.cons,
            "risks": result.risks,
            "confidence": result.confidence,
            "final_report": final_report,
        }

    except Exception as exc:
        errors = list(state.get("errors", []))
        errors.append(f"[final_decision] {type(exc).__name__}: {exc}")

        fallback_report = _build_final_report(
            {**state, "overall_score": overall_score},
            {
                "overall_score": overall_score,
                "recommendation": "Maybe",
                "reasoning": f"Decision agent failed: {exc}",
                "pros": [],
                "cons": [],
                "risks": [str(exc)],
                "confidence": 0.0,
            },
        )

        return {
            "overall_score": overall_score,
            "recommendation": "Maybe",
            "reasoning": f"Decision agent encountered an error: {exc}",
            "pros": [],
            "cons": [],
            "risks": [str(exc)],
            "confidence": 0.0,
            "final_report": fallback_report,
            "errors": errors,
        }
